### ISSUE TITLE
Player character can move through obstacles

### ISSUE THREAD

**Issue by Nun-z** [snaphat/final_fantasy_vi_widescreen#17]
![Screenshot_20210430-212601_Xbox](https://user-images.githubusercontent.com/54733172/116770843-4dacfc80-a9fb-11eb-951c-cea106f21752.jpg)

**Comment by snaphat** [comment]
That's purposeful at the moment (there's modification cheats for that toward the top of the asm that can be commented out)

**Comment by Nun-z** [comment]
Thank you.

**Comment by snaphat** [comment]
Though keep in mind that this is unfinished even with that disabled!

**Comment by Nun-z** [comment]
So far it has been very playable.  I just made it to Figaro Castle.

**Comment by snaphat** [comment]
I can tell you that I know figaro's cutscene is all kinds of messed up, no clue if others are. Check the open reports to see issues I've found so far with various things
